httpd/hub/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from hub import views

urlpatterns = [
    # root
    path('', views.archive, name='archive'),

    # import network
    path('import', views.import_network, name='import_network'),

    # EPANET archive
    path('epanet_archive', views.epanet_archive, name='epanet_archive'),

    # explore network
    path('network/<int:network_id>/explore', views.explore, name='explore'),

    # export network (GIS files)
    path('network/<int:network_id>/export_gis', views.export_gis, name='export_gis'),

    # analysis archive
    path('archive', views.archive, name='archive'),

    # hub
    path('hub', views.archive, name='hub'),

    # new analysis
    path('new', views.new, name='new'),

    # download analysis
    path('analysis/<int:analysis_id>/download', views.download_analysis, name='download_analysis'),

    # delete analysis
    path('analysis/<int:analysis_id>/delete', views.delete, name='delete'),

    # delete network
    path('network/<int:network_id>/delete', views.delete_network, name='delete_network'),

    # cancel analysis
    path('analysis/<int:analysis_id>/cancel', views.cancel, name='cancel'),

    # visualize result
    path('analysis/<int:analysis_id>/visualize', views.visualize_result, name='visualize_result'),

    # utilize built-in login/logout views
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

    # built-in admin interface
    path('admin/', admin.site.urls),
]

httpd/hub/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class WMRatUser(AbstractUser):
    pass

class WMNetwork(models.Model):
    name = models.CharField(max_length=64)

    user = models.ForeignKey(WMRatUser, on_delete=models.CASCADE)

    uploaded_at = models.DateTimeField(auto_now_add=True)

    epsg_code = models.IntegerField()

class Analysis(models.Model):
    # analysis name
    name = models.CharField(max_length=64)

    # analysis type
    analysis_type = models.CharField(max_length=64)

    # user
    user = models.ForeignKey(WMRatUser, on_delete=models.RESTRICT)

    # network
    wm_network = models.ForeignKey(WMNetwork, on_delete=models.RESTRICT)

    # input
    input_json = models.JSONField()

    # processing stati
    STATUS_SUCCESS = 0
    STATUS_FAILED = 1
    STATUS_QUEUED = 2
    STATUS_PROCESSING = 3
    STATUS_CANCELLED = 4
    STATUS_CANCELLING = 5

    STATUS = (
        (STATUS_SUCCESS, 'Success'),
        (STATUS_FAILED, 'Failed'),
        (STATUS_QUEUED, 'Queued'),
        (STATUS_PROCESSING, 'Processing'),
        (STATUS_CANCELLED, 'Cancelled'),
        (STATUS_CANCELLING, 'Cancelling'),
    )

    # processing status
    proc_status = models.PositiveSmallIntegerField(choices=STATUS)

    # RQ job (uuid4)
    job_id = models.CharField(max_length=36)

    # processing id
    proc_pid = models.IntegerField(blank=True, null=True)

    # submission date
    submitted = models.DateTimeField()

    # processing duration
    duration_s = models.FloatField() 

    # info message
    info_msg = models.CharField(max_length=256)

    def get_analysis_status_str(self):
        return Analysis.STATUS[self.proc_status][1]

httpd/hub/forms.py
from django import forms

class EPANETUploadFileForm(forms.Form):
    epanet_model_name = forms.CharField(max_length=64)
    epanet_file = forms.FileField()

httpd/hub/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect, HttpResponseForbidden, HttpResponseBadRequest, HttpResponseServerError
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.utils.timezone import make_aware
from django.conf import settings
from django.core.paginator import Paginator

from .forms import EPANETUploadFileForm

from django_rq import job
import django_rq
from rq import cancel_job

import datetime as dt
import json
import uuid
import glob
import os
import subprocess as sp
from pathlib import Path
import shutil
import time
import pandas as pd
import sys
import numpy as np
from pyproj import CRS
import signal

from hub.models import Analysis, WMNetwork

import epanet_util as enu

@login_required
def archive(request):
    analyses = Analysis.objects.filter()
    analyses = analyses.order_by('-submitted')

    paginator = Paginator(analyses, settings.ROWS_PER_PAGE)

    page_nr = request.GET.get('p')
    page_obj = paginator.get_page(page_nr)

    #NOTE: maybe not needed ... (useful for search) ...
    query_list = []
    for key in request.GET.keys():
        if key == 'p':
            continue

        val = request.GET.get(key)
        if val:
            query_list.append(key + '=' + val)

    query_str = '&'.join(query_list)

    context = {
        'page_title': "WMRAT: Water Management Resilience Analysis Toolkit",
        'page_obj': page_obj,
        'query_str': query_str,
    }

    return render(request, 'archive.html', context)

@login_required
def epanet_archive(request):
    networks = WMNetwork.objects.filter()
    networks = networks.order_by('-uploaded_at')

    paginator = Paginator(networks, settings.ROWS_PER_PAGE)

    page_nr = request.GET.get('p')
    page_obj = paginator.get_page(page_nr)

    # maybe not needed ... (useful for search) ...
    query_list = []
    for key in request.GET.keys():
        if key == 'p':
            continue

        val = request.GET.get(key)
        if val:
            query_list.append(key + '=' + val)

    query_str = '&'.join(query_list)

    context = {
        'page_title': 'WMRAT: Water Management Networks Archive',
        'page_obj': page_obj,
        'query_str': query_str,
    }

    #XXX todo
    return render(request, 'epanet_archive.html', context)

def viz_single_pipe_failure_epanet(analysis, request):
    network = analysis.wm_network

    network_path = settings.WMRAT_NETWORK_DIR / str(network.id)

    with open(network_path / 'gis' / 'links.geojson') as f:
        geojson_links = json.load(f)

    with open(network_path / 'gis' / 'nodes.geojson') as f:
        geojson_nodes = json.load(f)

    #TODO: hacky ... (we do that 2x)
    analysis_path = settings.WMRAT_ANALYSIS_DIR / str(analysis.id)
    new_results_name = f'{analysis.id}_{analysis.name}'.replace(' ', '_')

    #print(geojson_links)

    success, val = get_analyses_info_dict_with_defaults()
    if not success:
        err_str = val
        return HttpResponseServerError(err_str)

    analyses_info_all = val

    #print(analyses_info_all)

    analyses_info = analyses_info_all[analysis.analysis_type]

    file_name = analyses_info['output']['file_name']
    property_name = analyses_info['output']['property_name']

    pretty_analysis_type = analyses_info['pretty']

    pretty_output_name = analyses_info['output']['pretty']

    json_path = analysis_path / new_results_name / file_name

    #XXX: currently we only support to append to links
    with open(json_path) as f:
        link_infos = json.load(f)

    link_info_list = []
    for link_name, junctions_impacted in link_infos.items():
        if len(junctions_impacted) > 0:
            link_info_list.append([link_name, junctions_impacted])

    link_info_list = sorted(link_info_list, key=lambda x: x[1], reverse=True)

    print(link_info_list)

    #XXX
    print('len; XXX: what if result less then #pipes? had rewrite', len(link_info_list))

    #XXX: move somewhere else
    colors = {
        'PIPE': '#0000ff',
        'PUMP': '#00ff00',
        'VALVE': '#ff0000',
        'JUNCTION': '#000099',
        'RESERVOIR': '#990000',
        'TANK': '#009900',
    }

    context = {
        'default_color_ramp': ('#ff0000', '#00ff00'),
        'page_title': 'Result', #TODO: better name
        'links': geojson_links,
        'nodes': geojson_nodes,
        'analysis': analysis,
        'colors': colors,
        'pretty_analysis_type': pretty_analysis_type,
        'network': network, #XXX?
        'result': link_info_list,
        'pretty_output_name': pretty_output_name,
    }

    return render(request, 'viz_single_pipe_failure_epanet.html', context)

def viz_single_pipe_failure_graph(analysis, request):
    network = analysis.wm_network

    network_path = settings.WMRAT_NETWORK_DIR / str(network.id)

    with open(network_path / 'gis' / 'links.geojson') as f:
        geojson_links = json.load(f)

    with open(network_path / 'gis' / 'nodes.geojson') as f:
        geojson_nodes = json.load(f)

    #TODO: hacky ... (we do that 2x)
    analysis_path = settings.WMRAT_ANALYSIS_DIR / str(analysis.id)
    new_results_name = f'{analysis.id}_{analysis.name}'.replace(' ', '_')

    #print(geojson_links)

    success, val = get_analyses_info_dict_with_defaults()
    if not success:
        err_str = val
        return HttpResponseServerError(err_str)

    analyses_info_all = val

    #print(analyses_info_all)

    analyses_info = analyses_info_all[analysis.analysis_type]

    file_name = analyses_info['output']['file_name']
    property_name = analyses_info['output']['property_name']

    pretty_analysis_type = analyses_info['pretty']

    pretty_output_name = analyses_info['output']['pretty']

    json_path = analysis_path / new_results_name / file_name

    #XXX: currently we only support to append to links
    with open(json_path) as f:
        link_infos = json.load(f)

    link_info_list = []
    for link_name, ebcq_val in link_infos.items():
        if ebcq_val > 0:
            link_info_list.append([link_name, ebcq_val])

    link_info_list = sorted(link_info_list, key=lambda x: x[1])

    #XXX
    print('len; XXX: what if result less then #pipes? had rewrite', len(link_info_list))

    #XXX: move somewhere else
    colors = {
        'PIPE': '#0000ff',
        'PUMP': '#00ff00',
        'VALVE': '#ff0000',
        'JUNCTION': '#000099',
        'RESERVOIR': '#990000',
        'TANK': '#009900',
    }

    context = {
        'default_color_ramp': ('#ff0000', '#00ff00'),
        'page_title': 'Result', #TODO: better name
        'links': geojson_links,
        'nodes': geojson_nodes,
        'analysis': analysis,
        'colors': colors,
        'pretty_analysis_type': pretty_analysis_type,
        'network': network, #XXX?
        'result': link_info_list,
        'pretty_output_name': pretty_output_name,
    }

    return render(request, 'viz_single_pipe_failure_graph.html', context)

def viz_multi_pipe_failure_graph(analysis, request):
    network = analysis.wm_network

    network_path = settings.WMRAT_NETWORK_DIR / str(network.id)

    with open(network_path / 'gis' / 'links.geojson') as f:
        geojson_links = json.load(f)

    with open(network_path / 'gis' / 'nodes.geojson') as f:
        geojson_nodes = json.load(f)

    #TODO: hacky ... (we do that 2x)
    analysis_path = settings.WMRAT_ANALYSIS_DIR / str(analysis.id)
    new_results_name = f'{analysis.id}_{analysis.name}'.replace(' ', '_')

    #print(geojson_links)

    success, val = get_analyses_info_dict_with_defaults()
    if not success:
        err_str = val
        return HttpResponseServerError(err_str)

    analyses_info_all = val

    #print(analyses_info_all)

    analyses_info = analyses_info_all[analysis.analysis_type]

    file_name = analyses_info['output']['file_name']
    property_name = analyses_info['output']['property_name']

    pretty_analysis_type = analyses_info['pretty']

    pretty_output_name = analyses_info['output']['pretty']

    #XXX: here different other stuff mostly same
    json_path = analysis_path / new_results_name / 'data.json'

    #XXX: currently we only support to append to links
    with open(json_path) as f:
        result_json = json.load(f)

    result_list = []
    for entry in result_json:
        list_item = [
            entry['pipes'],
            int(entry['rank_G']),
            int(entry['rank_H']),
            entry['hyd_failure'],
        ]
        result_list.append(list_item)

    print(result_list)

    #XXX
    #print('len; XXX: what if result less then #pipes? had rewrite', len(link_info_list))

    #XXX: move somewhere else
    colors = {
        'PIPE': '#0000ff',
        'PUMP': '#00ff00',
        'VALVE': '#ff0000',
        'JUNCTION': '#000099',
        'RESERVOIR': '#990000',
        'TANK': '#009900',
    }

    context = {
        'default_color_ramp': ('#ff0000', '#00ff00'),
        'page_title': 'Result', #TODO: better name
        'links': geojson_links,
        'nodes': geojson_nodes,
        'analysis': analysis,
        'colors': colors,
        'pretty_analysis_type': pretty_analysis_type,
        'network': network, #XXX?
        'result': result_list,
        'pretty_output_name': pretty_output_name,
    }

    return render(request, 'viz_multi_pipe_failure_graph.html', context)

def viz_single_pipe_leakage(analysis, request):
    network = analysis.wm_network

    network_path = settings.WMRAT_NETWORK_DIR / str(network.id)

    with open(network_path / 'gis' / 'links.geojson') as f:
        geojson_links = json.load(f)

    with open(network_path / 'gis' / 'nodes.geojson') as f:
        geojson_nodes = json.load(f)

    #TODO: hacky ... (we do that 2x)
    analysis_path = settings.WMRAT_ANALYSIS_DIR / str(analysis.id)
    new_results_name = f'{analysis.id}_{analysis.name}'.replace(' ', '_')

    #print(geojson_links)

httpd/hub/templates/archive.html
{% extends "base.html" %}

{% block content %}

<!-- XXX: this should go in <head> ... -->
<meta http-equiv="refresh" content="5">

<div class="container-fluid">

{% if page_obj %}

<div class="row">

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Type</th>
                <th scope="col">Network</th>
                <th scope="col">Date</th>
                <th scope="col">Status</th>
                <th scope="col">Info</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for analysis in page_obj %}
            <tr>
                <!-- analysis meta information -->
                <td class="align-middle">{{ analysis.id }}</td>
                <td class="align-middle">{{ analysis.name }}</td>
                <td class="align-middle">{{ analysis.analysis_type }}</td>
                <td class="align-middle"><a href="network/{{ analysis.wm_network.id}}/explore">{{ analysis.wm_network.name }}</a></td>
                <td class="align-middle">{{ analysis.submitted|date:"Y.m.d" }}</td>

                <!-- status -->
                {% if analysis.proc_status == 0 %}
                <td class="align-middle">
                    <button class="btn btn-success btn-sm" type="button" disabled>{{ analysis.get_analysis_status_str }}</button>
                </td>
                {% elif analysis.proc_status == 1 %}
                <td class="align-middle">
                    <button class="btn btn-danger btn-sm" type="button" disabled>{{ analysis.get_analysis_status_str }}</button>
                </td>
                {% elif analysis.proc_status == 2 %}
                <td class="align-middle">
                    <button class="btn btn-warning btn-sm" type="button" disabled>{{ analysis.get_analysis_status_str }}</button>
                </td>
                {% elif analysis.proc_status == 3 %}
                <td class="align-middle">
                    <button class="btn btn-primary btn-sm" type="button" disabled><span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span> {{ analysis.get_analysis_status_str }}</button>
                </td>
                {% elif analysis.proc_status == 4 %}
                <td class="align-middle">
                    <button class="btn btn-warning btn-sm" type="button" disabled>{{ analysis.get_analysis_status_str }}</button>
                </td>
                {% else %}
                <td class="align-middle">
                    <button class="btn btn-warning btn-sm" type="button" disabled><span class="spinner-grow spinner-grow-sm" role="status" aria-hidden="true"></span> {{ analysis.get_analysis_status_str }}</button>
                </td>
                {% endif %}

                <!-- info -->
                <td class="align-middle">{{ analysis.info_msg }}{% if analysis.proc_status == 0 or analysis.proc_status == 1 %} ({{ analysis.duration_s|floatformat:0 }}s) {% endif %}</td>

                <!-- visualize -->
                {% if analysis.proc_status == 0 or analysis.proc_status == 1 %}
                <td class="align-middle"><a class="text-decoration-none" href="analysis/{{analysis.id}}/visualize"><i class="fas fa-eye"></i> show</a></td>
                {% else %}
                <td></td>
                {% endif %}

                <!-- cancel -->
                {% if analysis.proc_status == 2 or analysis.proc_status == 3 %}
                <td class="align-middle">
                    {% if user.id == analysis.user.id or user.is_superuser %}
                    <form method="post" action=" {% url 'cancel' analysis_id=analysis.id %}">
                        {% csrf_token %}
                        {% if analysis.proc_status == 2 %}
                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-stop"></i> cancel</button>
                        {% else %}
                        <button type="submit" class="btn btn-danger btn-sm"><i class="fas fa-stop"></i> stop</button>
                        {% endif %}
                    </form>
                    {% endif %}
                </td>
                {% else %}
                <td></td>
                {% endif %}

                <!-- download -->
                {% if analysis.proc_status == 0 or analysis.proc_status == 1 %}
                <td class="align-middle"><a class="text-decoration-none" href="analysis/{{analysis.id}}/download"><i class="fas fa-download"></i> download</a></td>
                {% else %}
                <td></td>
                {% endif %}

                <!-- delete -->
                {% if analysis.proc_status == 0 or analysis.proc_status == 1 or analysis.proc_status == 4 %}
                <td class="align-middle">
                    {% if user.id == analysis.user.id or user.is_superuser %}
                    <form method="post" action=" {% url 'delete' analysis_id=analysis.id %}">
                        {% csrf_token %}
                        <button type="submit" class="btn btn-warning btn-sm"><i class="fas fa-trash-can"></i> delete</button>
                    </form>
                    {% endif %}
                </td>
                {% else %}
                <td></td>
                {% endif %}

            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

<div class="row">
<div class="col-md-12">

<nav aria-label="Page navigation example">
    <ul class="pagination pagination-sm justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?p=1&{{query_str}}">1</a></li>
        <li class="page-item">
            <a class="page-link" href="?p={{page_obj.previous_page_number}}&{{query_str}}" aria-label="Previous"><span aria-hidden="true">&laquo; Previous</span></a>
        </li>
        {% endif %}

        <li class="page-item"><a class="page-link" href="?p={{ page_obj.number }}&{{query_str}}">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?p={{page_obj.next_page_number}}&{{query_str}}" aria-label="Next"><span aria-hidden="true">Next &raquo;</span></a>
        </li>
        <li class="page-item"><a class="page-link" href="?p={{ page_obj.paginator.num_pages }}&{{query_str}}">{{ page_obj.paginator.num_pages }}</a></li>
        {% endif %}
    </ul>
</nav>

</div>
</div>

<div class="row">
<div class="col-md-12">
    <p style="text-align: center; font-size: 14px">{{page_obj.paginator.count}} analys{% if page_obj.paginator.count > 1 %}es{% else %}is{% endif %}</p>
</div>
</div>

{% else %}
    <p style="margin-top: 32px; text-align: center;">No analyses. ☹️</p>
{% endif %}

</div>

{% endblock %}

httpd/hub/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>WMRat v24.02</title>

    <link href="{% static "awesome/all.css" %}" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://unpkg.com/leaflet/dist/leaflet.css" />

    <script src="https://unpkg.com/leaflet/dist/leaflet.js"></script>
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>

    <style>
        body {
            height: 100%;
            margin: 0px;
        }

        .header-title {
            margin-left: 20px;
            margin-bottom: 2px;
            font-weight: bold;
        }   

        .header {
            height: 56px;
        }

        .footer {
            height: 56px;
            position: fixed;
            bottom: 0;
            left: 0;
            width: 100%;
            color: #fff;
            background-color: #000;
            padding: 10px;
        }

        .container {
            height: calc(100vh - 112px);
            overflow-y: auto;
        }

        .main-view {
            height: calc(100vh - 112px);
            overflow-y: auto;
        }

        .table-container tbody tr:hover {
            background-color: #cce5ff;
        }

        .table-container tbody tr.table-active {
            background-color: #3366cc; /* Darker blueish color for clicked rows */
            color: #fff; /* White text for better contrast */
        }

        #map {
            height: calc(100vh - 112px);
        }

        .leaflet-tile-pane {
          -webkit-filter: grayscale(100%);
          filter: grayscale(100%);
        }
    </style>
</head>

<body>

<div class="header">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <a class="navbar-brand header-title" href="{% url 'archive' %}"><i class="fa-solid fa-faucet-drip" style="color: #21e1ff"></i><span style="color: #4d5eff;"> w</span><span style="color: #21e1ff">m</span><span style="color: #4d5eff">rat</span></a>
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'import_network' %}"><i class="fas fa-upload"></i> Import Network</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'epanet_archive' %}"><i class="fas fa-network-wired"></i> Network Archive</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'new' %}"><i class="fas fa-square-plus"></i> New Analysis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'archive' %}"><i class="fas fa-box-archive"></i> Analysis Results</a>
                </li>
            </ul>
        </div>
        <div class="ml-auto">
            <form class="d-flex" method="post" action="{% url 'logout' %}">
                {% csrf_token %}
                <button class="btn btn-danger"><i class="fas fa-sign-out-alt"></i> Logout</button>
            </form>
        </div>
    </nav>
</div>

{% block content %}
{% endblock %}

</body>
</html>

httpd/hub/templates/epanet_archive.html
{% extends "base.html" %}

{% block content %}

<div class="container-fluid">

{% if page_obj %}

<div class="row">

    <table class="table table-striped">
        <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">Name</th>
                <th scope="col">Upload date</th>
                <th scope="col"></th>
                <th scope="col"></th>
                <th scope="col"></th>
            </tr>
        </thead>
        <tbody>
            {% for network in page_obj %}
            <tr>
                <!-- network meta information -->
                <td class="align-middle">{{ network.id }}</td>
                <td class="align-middle">{{ network.name }}</td>
                <td class="align-middle">{{ network.uploaded_at|date:"Y.m.d" }}</td>

                <!-- explorer -->
                <td>
                <a class="btn btn-primary btn-sm" href="network/{{network.id}}/explore" role="button"><i class="fas fa-circle-nodes"></i> explore</a>
                </td>

                <!-- download -->
                <td>
                <a class="btn btn-warning btn-sm" href="network/{{network.id}}/export_gis" role="button"><i class="fas fa-circle-nodes"></i> download (GIS)</a>
                </td>

                <!-- XXX -->
                <td>
                <!--
                {% if user.id == network.user.id or user.is_superuser %}
                -->
                <form method="post" action=" {% url 'delete_network' network_id=network.id %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-warning btn-sm"><i class="fas fa-trash-can"></i> delete</button>
                </form>
                {% endif %}
                </td>
            </tr>
            </tr>
            {% endfor %}
        </tbody>
    </table>

</div>

<div class="row">
<div class="col-md-12">

<nav aria-label="Page navigation example">
    <ul class="pagination pagination-sm justify-content-center">
        {% if page_obj.has_previous %}
        <li class="page-item"><a class="page-link" href="?p=1&{{query_str}}">1</a></li>
        <li class="page-item">
            <a class="page-link" href="?p={{page_obj.previous_page_number}}&{{query_str}}" aria-label="Previous"><span aria-hidden="true">&laquo; Previous</span></a>
        </li>
        {% endif %}

        <li class="page-item"><a class="page-link" href="?p={{ page_obj.number }}&{{query_str}}">{{ page_obj.number }}</a></li>

        {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?p={{page_obj.next_page_number}}&{{query_str}}" aria-label="Next"><span aria-hidden="true">Next &raquo;</span></a>
        </li>
        <li class="page-item"><a class="page-link" href="?p={{ page_obj.paginator.num_pages }}&{{query_str}}">{{ page_obj.paginator.num_pages }}</a></li>
        {% endif %}
    </ul>
</nav>

</div>
</div>

<div class="row">
<div class="col-md-12">
    <p style="text-align: center; font-size: 14px">{{page_obj.paginator.count}} network{% if page_obj.paginator.count > 1 %}s{% endif %}</p>
</div>
</div>

{% else %}
    <p style="margin-top: 32px; text-align: center;">No networks. ☹️</p>
{% endif %}

</div>

{% endblock %}

httpd/hub/templates/import.html
{% extends "base.html" %}

{% block content %}

<div class="container">

<div class="row" style="margin-top: 32px;">

<form action="{% url 'import_network' %}" method="post" id="main_form" enctype="multipart/form-data">

    {% csrf_token %}

    <div class="form-row">

    <div class="form-group col-md-4">
        <label for="epanet_model_name" class="form-label">Network name</label>
        <input type="text" class="form-control" id="epanet_model_name" name="epanet_model_name" value="EPANET Test Network">
    </div>

    <div class="form-group col-md-4">
        <label for="id_epanet_file" class="form-label">Select file</label>
        <input type="file" class="form-control" name="epanet_file" required id="id_epanet_file">
    </div>

    <div class="form-group col-md-4">
        <label for="id_epsg" class="form-label">EPSG Code</label>
        <input type="text" class="form-control" id="id_epsg" name="id_epsg" value="31254">
    </div>

    </div>

    <button id="thebutton" type="submit" class="btn btn-success"><i class="fas fa-upload"></i> Import</button>
</form>

</div>

</div>

<script>
    console.log("...");
</script>

{% endblock %}